version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build: .
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    restart: always
    container_name: fede_postgres
    hostname: database.local
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      VIRTUAL_HOST: database.local
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:cached
    shm_size: '2gb'
