version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    restart: always
    container_name: fede_postgres
    hostname: database.local
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:cached
    shm_size: '2gb'
