version: '3.8'

volumes:
  postgres-data:
  redis-data:

services:
  app:
    build: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    restart: always
    container_name: fede_postgres
    hostname: database.local
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:cached
    shm_size: '2gb'

  redis:
    image: redis:alpine3.16
    container_name: fede_cache
    hostname: cache.local
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass admin
    volumes:
      - redis-data:/var/lib/redis/data:cached
